### ISSUE TITLE
Definir el proyecto a realizar

### ISSUE THREAD

**Issue by denisse989** [Stacys-Malibu/Stacys-Malibu#1]
-Buscar en SICOES proyectos de sistemas
-Evitar usar proyectos pasados
-Definir como equipo que proyecto de SICOES se va a trabajar 
-Mostrar proyecto al docente

**Comment by Llubitza-Linares** [comment]
Se definió el proyecto el día viernes 12

**Comment by Llubitza-Linares** [comment]
Existieron algunas otras opciones de proyectos pero se optó por cual se consideró mejor

**Comment by denisse989** [comment]
Se eligió el proyecto: Contratación De Una Empresa Para El Servicio De La Aplicación Del Examen De Ascenso De Categoría Vía Web Para Los Departamentos De Chuquisaca, Potosí, Santa Cruz, Beni Y Pando Gestión 2020
