### ISSUE TITLE
Unir base de datos con Android - Eliminar

### ISSUE THREAD

**Issue by denisse989** [Stacys-Malibu/Stacys-Malibu#40]
Unir la base de datos para poder eliminar usuarios regulares de la base de datos.
* Solo debe poder eliminarse desde la cuenta del usuario maestro.
* Se debe visualizar la eliminación de participantes en la lista de participantes para el usuario maestro y administrador.

**Comment by Llubitza-Linares** [comment]
En el proceso para realizar la conexión del base de datos existieron muchos problemas, finalmente optamos por realizar todo en SQLite
