### ISSUE TITLE
Unir base de datos con Android - Editar

### ISSUE THREAD

**Issue by denisse989** [Stacys-Malibu/Stacys-Malibu#41]
Unir la base de datos para que se pueda editar desde el usuario maestro a los usuarios regulares.
* Se necesita que se edite en la base de datos
*  Se tiene que visualizar en la lista de participantes el cambio

**Comment by Llubitza-Linares** [comment]
Al momento de editar en nuestra aplicación salieron algunas complicaciones pero finalmente pudimos hacer que funcione de forma exitosa
