### ISSUE TITLE
Pruebas de Unidad - Identificar los casos

### ISSUE THREAD

**Issue by denisse989** [Stacys-Malibu/Stacys-Malibu#42]
Identificar los 10 casos requeridos para la evaluación de nuestro proyecto.
Para lo cual se necesita seguir las siguientes características en los casos a tomar en cuenta para las pruebas unitarias:
* Identificar los casos (funciones o métodos ).
* Que sean métodos o funciones únicos (que no dependan de ninguna otra función externa).
* Que se ejecute de manera veloz (milisegundos).

**Comment by Llubitza-Linares** [comment]
Identificar los casos que usaríamos se realizó de una manera bastante rápida, para cada uno de estos casos se espera con seguir la aprobación necesaria.
