### ISSUE TITLE
Github action para realizar el paquete final

### ISSUE THREAD

**Issue by Llubitza-Linares** [Stacys-Malibu/Stacys-Malibu#45]
Realizar el código en el archivo .yaml dentro del proyecto en la carpeta .github/workflows.
* El código deberá generar el paquete final, en este caso será un APK de manera automática por medio de Github Action
* Al hacer un pull request este apk debe salir de la siguiente manera:

![image](https://user-images.githubusercontent.com/60879365/146867831-9738b074-df26-4232-b3d5-6ce182ea9b15.png)
 
* Donde al apretar en debug apk se debe descargar el apk.zip y al descomprimir se tendrá el apk correspondiente a la aplicación.

**Comment by denisse989** [comment]
Se logro realizar la creación del APK con github action el 20-12-2021.
* El archivo se encuentra en el ultimo workflow con el nombre :
    FINAL PARA LA PRESENTACION DEL DIA MARTES 21-12-2021. runOnGitHub #15
