### ISSUE TITLE
Pruebas de Unidad - Pruebas de la 1 a la 3

### ISSUE THREAD

**Issue by denisse989** [Stacys-Malibu/Stacys-Malibu#47]
Realizar el código para las primeras 3 pruebas de unidad dentro del proyecto en la carpeta com.example.stacy (test) en el file ExampleUnitTest.
Loas 3 primeros casos son:
* AdapterItem: En el cual se probara el método getItem que pide como parámetro un int de la clase AgregarListViewAdapter el cual debe devolver un Usuario de la lista de usuarios según la posición que se pide en el parámetro de getItem.
* AdapterItemID: En el cual se probara el metodo getItemId que pide como parámetro un int de la clase AgregarListViewAdapter el cual debe devolver un int con el Id del Usuario según la posición que se pide en el parámetro.
*  UsuarioNombre: En el cual se probara el metodo getNombre de la clase AgregarListViewAdapter el cual debe devolver el nombre del Usuario

**Comment by Llubitza-Linares** [comment]
Estos 3 primeros casos de uso se usará el método get donde buscamos que nos devuelva de manera correcta el elemento buscado. Esto fue realizado el día 17/12.
