### ISSUE TITLE
Pruebas de Unidad - 4 a la 6

### ISSUE THREAD

**Issue by denisse989** [Stacys-Malibu/Stacys-Malibu#48]
Realizar el código para las pruebas 4 a la 6 pruebas de unidad dentro del proyecto en la carpeta com.example.stacy (test) en el file ExampleUnitTest.
Los 3 casos son:
* UsuarioApellido: En el cual se probara el método getApellido que  no pide parámetros de la clase Usuarios el cual debe devolver el Apellido de los datos del usuario que se encuentra dentro del objeto Usuario.
* UsuarioTipoExamen: En el cual se probara el metodo getITipoE que no pide parámetros de la clase Usuarios el cual debe devolver el tipo de examen del objeto Usuario .
*  UsuarioId: En el cual se probara el método getId de la clase Usuario el cual debe devolver el id con el que se identifica al objeto Usuario creado.

**Comment by Llubitza-Linares** [comment]
Estos 3 primeros casos de uso usará el método get, al momento de hacer su aprobación salieron algunas fallas pero se arreglaron ese momento . Esto fue realizado el día 17/12.
