### ISSUE TITLE
Pruebas de Unidad - De la 7 a la 10

### ISSUE THREAD

**Issue by denisse989** [Stacys-Malibu/Stacys-Malibu#49]
Realizar el código para las ultimas 4 pruebas de unidad dentro del proyecto en la carpeta com.example.stacy (test) en el file ExampleUnitTest.
Los 4 casos son:
* ExamenCategoria: En el cual se probara el método getCategoria que no pide parámetros de la clase Examen el cual debe devolver la categoría del objeto Examen .
* ExamenCantidad: En el cual se probara el método getICantidad que no pide parámetro de la clase Examen el cual debe devolver un String con la cantidad de exámenes del objeto Examen.
*  ExamenId: En el cual se probara el método getId de la clase Examen el cual debe devolver el id del objeto Examen.
* ExamenAdapter: En el cual se prueba el metodo getItem de la clase AgregarListViewAdapter3 donde se tiene una lista del objeto Usuario y al pedirle un ítem con parámetro de la posición que tiene el Usuario en la lista debe devolver el Usuario que se encuentra en esa posición.

**Comment by Llubitza-Linares** [comment]
Estos 3 primeros casos de uso esperamos  que nos devuelva de manera correcta el elemento que estamos buscando. Esto fue realizado el día 17/12.
