### ISSUE TITLE
Preguntar sobre dudas al docente

### ISSUE THREAD

**Issue by denisse989** [Stacys-Malibu/Stacys-Malibu#5]
- Elección de proyecto que se tomo de SICOES 
- Requerimientos que se deben cumplir y cuales podemos saltarnos.

**Comment by Llubitza-Linares** [comment]
Las preguntas fueron realizadas el día lunes 15

**Comment by Llubitza-Linares** [comment]
Las dudas fueron aclaradas y eso nos ayudo a seguir con el avance del proyecto
